apiVersion: v1
kind: Service
metadata:
  name: db-status
  namespace: db-status
spec:
  selector:
    app.kubernetes.io/name: db-status
  ports:
    - name: http
      port: 8080
      targetPort: http
