#!/usr/bin/env bash
# Print a complete Teleport join token for the db-status bot, with the
# cluster's ServiceAccount signing keys already filled in.
#
#   scripts/make-token.sh | tctl create -f -
#   tctl bots add db-status --roles=db-status --token=db-status
#
# Reads the keys from the CURRENT kubectl context (kubectl get --raw
# /openid/v1/jwks), so run it while pointed at the cluster the pod will run in.
#
# join_method: kubernetes with static_jwks — the Auth Service verifies the pod's
# projected ServiceAccount token against these keys, so it works when the Auth
# Service cannot reach the cluster (Teleport Cloud). If the cluster's keys
# rotate or the cluster is rebuilt, run this again and recreate the token.
set -euo pipefail

bot="${BOT_NAME:-db-status}"
jwks=$(kubectl get --raw /openid/v1/jwks | tr -d '\n')
[ -n "$jwks" ] || { echo "make-token.sh: could not read /openid/v1/jwks from the current context" >&2; exit 1; }
ctx=$(kubectl config current-context 2>/dev/null || echo unknown)

cat <<EOF
# Join token for the ${bot} bot. Generated by scripts/make-token.sh from
# kubectl context "${ctx}". Contains public keys only.
kind: token
version: v2
metadata:
  name: ${bot}
spec:
  roles: [Bot]
  bot_name: ${bot}
  join_method: kubernetes
  kubernetes:
    type: static_jwks
    static_jwks:
      jwks: |
        ${jwks}
    allow:
      - service_account: "${bot}:${bot}"
EOF
